apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: youtube-ui
  namespace: {{ .Values.argoCDNamespace }}
spec:
  project: {{ .Values.project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace }}
  source:
    path: charts/youtube-ui
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
    helm: {{ .Values.source.helm }}
  syncPolicy: {{ .Values.syncPolicy }}