apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-ui
  namespace: argo-cd
spec:
  project: app-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  source:
    path: cluster/boostrap
    repoURL: git@github.com:bpn2k4/argocd-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - CreateNamespace=true
      - Validate=false
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
